var callgraph = {
	nodes: [
		 { data: { id: 'Fibonacci' } },
		 { data: { id: 'len' } },
		 { data: { id: 'isPath' } },
		 { data: { id: 'make' } },
		 { data: { id: 'uint64' } },
		 { data: { id: 'findRootFunctions' } },
		 { data: { id: 'main' } },
		 { data: { id: 'instrument' } },
		 { data: { id: 'panic' } },
		 { data: { id: 'uint' } },
		 { data: { id: 'append' } },
		 { data: { id: 'NewResource' } },
		 { data: { id: 'usage' } },
		 { data: { id: 'searchFiles' } },
		 { data: { id: 'NewExporter' } },
		 { data: { id: 'NewTracingState' } },
		 { data: { id: 'parsePath' } },
		 { data: { id: 'FibonacciHelper' } },
		 { data: { id: 'buildCallGraph' } },
		 { data: { id: 'generatecfg' } },
	],
	edges: [
		 { data: { id: 'e0', source: 'buildCallGraph', target: 'panic' } },
		 { data: { id: 'e1', source: 'main', target: 'buildCallGraph' } },
		 { data: { id: 'e2', source: 'main', target: 'parsePath' } },
		 { data: { id: 'e3', source: 'main', target: 'FibonacciHelper' } },
		 { data: { id: 'e4', source: 'isPath', target: 'isPath' } },
		 { data: { id: 'e5', source: 'NewTracingState', target: 'NewResource' } },
		 { data: { id: 'e6', source: 'main', target: 'Fibonacci' } },
		 { data: { id: 'e7', source: 'main', target: 'searchFiles' } },
		 { data: { id: 'e8', source: 'main', target: 'findRootFunctions' } },
		 { data: { id: 'e9', source: 'parsePath', target: 'instrument' } },
		 { data: { id: 'e10', source: 'main', target: 'make' } },
		 { data: { id: 'e11', source: 'main', target: 'usage' } },
		 { data: { id: 'e12', source: 'Fibonacci', target: 'uint64' } },
		 { data: { id: 'e13', source: 'main', target: 'append' } },
		 { data: { id: 'e14', source: 'main', target: 'len' } },
		 { data: { id: 'e15', source: 'main', target: 'generatecfg' } },
		 { data: { id: 'e16', source: 'NewTracingState', target: 'NewExporter' } },
		 { data: { id: 'e17', source: 'Fibonacci', target: 'uint' } },
	]
};